name: Check for update master branch

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */5 * *"

jobs:
  check_version:
    name: Check for update master branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.OBLAK_BOT_TOKEN }}
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Check for update master branch
        run: |
          ./update_master.sh