name: Check for new RedisInsight version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check_version:
    name: Check for new version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.OBLAK_BOT_TOKEN }}
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Check for new version
        run: |
          .github/scripts/check-release-version.bash
